site_name: Constantine Rudenko
site_subname: personal website
site_url: https://constantinerudenko.github.io/
theme:
    name: null
    custom_dir: "theme/"
    include_search_page: true
extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - js/configMathjax.js
    - js/menuPictures/menuPictures.js
    - js/image-row.js
plugins:
    - search
    - mkdocs-nav-enhancements
    - mermaid2
markdown_extensions:
    - admonition
    - def_list
    - mdx_spanner # rowspan and colspan in markdown tables
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          guess_lang: False
          use_pygments: True
          noclasses: True
          pygments_style: default
    - pymdownx.inlinehilite
    - pymdownx.superfences:
          # make exceptions to highlighting of code:
          custom_fences: # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#custom-fences
              - name: mermaid
                class: mermaid
                format: !!python/name:mermaid2.fence_mermaid
